packages/frontend/src/App.tsx, packages/frontend/src/components/Hero/Hero.tsx
This is an issue with the current version of shared-ui we are using here.
Upgrading to the latest version is a big job as we have changed a lot in that time.
- Temporarily remove shared-ui Hero component, replace with custom containers.
Closes #109
=> fix(frontend): replace broken shared-ui hero layout

.github/workflows/ci.yml, .gitmodules, .vscode/settings.json, packages/hardhat/foundry.toml, packages/hardhat/hardhat.config.ts, packages/hardhat/package.json, packages/hardhat/remappings.txt, pnpm-lock.yaml
Add Foundry to `./packages/hardhat` for extensive testing.
- add foundry to machine if not installed:
```
curl -L https://foundry.paradigm.xyz | bash
``` 
- check for install
```
forge --version
```
- running tests located inside `./packages/hardhat/test/foundry/` 
```
forge test
``` 
- compile files located inside `./packages/hardhat/contracts/`
```
forge build
```
merge #120 first
=> feat(hardhat): add foundry to hardhat project

packages/frontend/.storybook/decorators/wagmiDecorator.jsx, packages/frontend/.storybook/main.cjs, pnpm-lock.yaml
Due to some lockfile inconsistencies, the build was attempting to use the new version of shared-ui, breaking `tsc` in the frontend package.
One of the wagmi exports also broke, not sure if related or not.
=> dependencies(frontend): lock shared-ui version

packages/frontend/src/components/CreateSwap/CreateSwap.tsx, packages/frontend/src/utils/evm.ts, packages/frontend/src/utils/index.ts
- Adds 2 toasts to communicate successful swaps.
- Adds `getEvmTxUrl` helper. I've left in other EVM chains in case we'd like to expand in the future.
- TX link works correctly
Closes #112.
=> feat(frontend): add success Toasts

packages/frontend/src/components/ConnectWallet/ConnectWallet.tsx, packages/frontend/src/components/CreateSwap/CreateSwap.stories.tsx, packages/frontend/src/components/CreateSwap/CreateSwap.tsx, packages/frontend/src/components/CreateSwapButtons/ApproveButton.tsx, packages/frontend/src/components/CreateSwapButtons/CreateSwapButtons.tsx, packages/frontend/src/components/CreateSwapButtons/SwitchNetworkButton.tsx, packages/frontend/src/components/FAQ/FAQ.tsx, packages/frontend/src/components/Footer/Footer.tsx, packages/frontend/src/components/Header/Header.tsx, packages/frontend/src/components/HeaderMenu/HeaderMenu.tsx, packages/frontend/src/components/Input/Input.stories.tsx, packages/frontend/src/components/TokenSelector/TokenSelector.tsx, packages/frontend/src/components/TokenSelector/useTokenSelector.tsx, packages/frontend/src/hooks/useAllowance.tsx, packages/frontend/src/hooks/useAnalytics.tsx, packages/frontend/src/hooks/useApprove.tsx, packages/frontend/src/hooks/useConnectWallet.tsx, packages/frontend/src/hooks/useCullQueries.tsx, packages/frontend/src/hooks/useQuote.tsx, packages/frontend/src/hooks/useTokenBalance.tsx, packages/frontend/src/hooks/useTokens.tsx, packages/frontend/src/hooks/useWalletBalance.tsx, packages/frontend/src/providers/SDKProvider.tsx, packages/frontend/src/providers/TokensProvider.tsx, packages/frontend/src/providers/WagmiProvider.tsx, packages/frontend/src/utils/tokens.ts, packages/frontend/tsconfig.json, packages/frontend/vite.config.ts
Sets up Tsconfig and Vite for absolute imports in the Frontend. This gives us much more readable, and scalable code. Updated the imports to match the new standard.
Closes #151
=> refactor(frontend): use absolute imports

packages/frontend/src/components/CreateSwapButtons/CreateSwapButtons.tsx, packages/frontend/src/hooks/useAllowance.tsx, packages/frontend/src/hooks/useApprove.tsx
Re-enables the approve button and updates the comparison logic. 
Not bug free. We certainly need to address situations when the user needs to approve again. This is a separate matter, as it might require a good way of communicating this to the user.
=> fix(frontend): approve button

packages/frontend/src/components/Button/Button.stories.tsx, packages/frontend/src/components/Button/Button.tsx
- Add `size` prop to Button
- Make `normal` default, so all the Swap Buttons are less tall
Closes #172
=> feat(frontend): reduce swap buttons height

packages/frontend/src/components/CreateSwap/CreateSwap.tsx, packages/frontend/src/components/CreateSwapButtons/CreateSwapButtons.tsx, packages/frontend/src/hooks/useQuote.tsx
- Handle Same Token Pairs in CreateSwap, we don't request a quote, change the button label and clear + disable the shift inputs
Closes #146
=> feat(frontend): handle same token pairs in create swap

packages/frontend/src/components/CreateSwapButtons/CreateSwapButtons.tsx, packages/frontend/src/hooks/useQuote.tsx, packages/frontend/src/utils/index.ts, packages/frontend/src/utils/isValidTokenAmount.ts
This PR adds improved handling for when the user enters amounts such as `'0'` or `'0.0'` or `'000'` etc.
- Add `isValidTokenAmount` util function
- Disable quote fetching when this function returns `false`
- Update Button Label when this function returns `false`
https://github.com/sideshiftfi/sifi/assets/128688932/e42541b1-a842-422f-8564-74cabd3dea89
Closes #178
=> feat(frontend): handle zero amounts for create swap

packages/frontend/src/components/CreateSwap/CreateSwap.tsx, packages/frontend/src/components/SwapInformation/SwapInformation.tsx, packages/frontend/src/components/SwapInformation/index.ts
- Move Gas Estimate (and the soon to be re-added USD value) to a SwapInformation Component
- Don't hide gas estimate when not connected, since it still works
- Add a loading state to avoid layout jumps
https://github.com/sideshiftfi/sifi/assets/128688932/c73abe3e-e194-419c-be7a-4966c94ac320
Closes #173
=> fix(frontend): layout jump when gas estimate changes

packages/frontend/.storybook/decorators/wagmiDecorator.jsx, packages/frontend/package.json, packages/frontend/src/components/CreateSwap/CreateSwap.tsx, packages/frontend/src/components/CreateSwapButtons/CreateSwapButtons.tsx, packages/frontend/src/hooks/useAllowance.tsx, packages/frontend/src/hooks/useApprove.tsx, packages/frontend/src/hooks/useQuote.tsx, packages/frontend/src/providers/WagmiProvider.tsx, pnpm-lock.yaml
- Upgrades wagmi to version 1.3, installs it's new peer dependency viem.
- Replaces all instances of ethers utils with viem equivalents
- Removes ethers dependency
- ~~WalletConnect wallet connection~~ (needs fixing separately)
=> chore(frontend): upgrade wagmi to 1.3.10

packages/frontend/package.json, packages/frontend/src/components/CreateSwap/CreateSwap.tsx, packages/frontend/src/components/TokenSelector/TokenSelector.tsx, packages/frontend/src/constants.ts, packages/frontend/src/hooks/useMulticallTokenBalance.tsx, packages/frontend/src/types.ts, pnpm-lock.yaml
- Introduces a new hook `useMulticallTokenBalance`, using viem's multicall functionality to fetch the users token balance.
- Passes formatted values to `TokenSelector`.
- Even with `multicall` we are asking quite a lot of our public RPC here, and we are sometimes being rate limited by the default wagmi RPC (Cloudflare-eth). This could be a bigger problem once we have multichain support.
=> feat(frontend): use viem multicall to fetch token balances

packages/hardhat/contracts/facets/UniV3Callback.sol, packages/hardhat/test/foundry/Curve.t.sol, packages/hardhat/test/foundry/KittyFacet.t.sol, packages/hardhat/test/foundry/LibKitty.t.sol, packages/hardhat/test/foundry/SifiDiamond.t.sol, packages/hardhat/test/foundry/UniV2LikeFacet.t.sol, packages/hardhat/test/foundry/UniV2RouterFacet.int.t.sol, packages/hardhat/test/foundry/UniV2RouterFacet.t.sol, packages/hardhat/test/foundry/UniV3Like.t.sol, packages/hardhat/test/foundry/WarpLink.t.sol, packages/hardhat/test/foundry/helpers/Arbitrum.sol, packages/hardhat/test/foundry/helpers/FacetTest.sol, packages/hardhat/test/foundry/helpers/Networks.sol, packages/hardhat/test/foundry/helpers/Polygon.sol
This PR adds support for Algebra, which is used by QuickSwap V3 on Polygon. Yes, they renamed the callback.
- refactor(hardhat): extract Networks test helper
- feat(hardhat): support algebra for univ3
=> quickswapv3

packages/frontend/.storybook/main.cjs, packages/frontend/.storybook/preview-head.html, packages/frontend/.storybook/preview.tsx, packages/frontend/package.json, packages/frontend/src/index.css, pnpm-lock.yaml
- Add Theme Support to Storybook, which now sets the default theme to dark
Closes #185
=> feat(storybook): add theme support

packages/frontend/src/providers/SwapFormProvider.tsx
Removes the default `fromAmount` value, so that the user is presented with empty input fields and a visible Max button.
--
This fixes the issue of welcoming users with a max error and insufficient balance states.
Previously, when arriving to the app:
Autofocus on `fromAmount` might be nice, but ShiftInput does not support it yet.
=> fix(frontend): don't use default fromAmount

packages/frontend/src/components/ConnectWallet/ConnectWallet.tsx, packages/frontend/src/components/CreateSwap/CreateSwap.tsx, packages/frontend/src/components/CreateSwapButtons/ApproveButton.tsx, packages/frontend/src/types.ts, packages/frontend/src/utils/getViemErrorMessage.ts, packages/frontend/src/utils/index.ts, packages/frontend/src/utils/parseErrorMessage.ts
- Uses Viem `shortMessage` field in toasts if it exists on a given error message.
- Changes message filter in existing error filtering function to match phrasing used in Viem error messages.
- Applies fix to token approval, and transaction sending.
=> feat(frontend): use short viem error messages

packages/frontend/src/AppProvider.tsx, packages/frontend/src/providers/SelectedChainProvider.tsx
- Sets default network to users network (if available)
- Falls back to Ethereum L1 if connected network is not supported
https://github.com/sideshiftfi/sifi/assets/112887817/4cc69699-3008-4d56-99cd-4ad6dd44e420
- See video
=> feat(frontend): default to user connected network

packages/frontend/src/components/CreateSwap/CreateSwap.tsx
Clears token amounts when the `fromToken` changes - fromToken is also a function of the token list, so this also acts as a reset on network change.
https://github.com/sideshiftfi/sifi/assets/112887817/9fc942dd-7eea-460c-a5cd-dc1d4fce351e
- Video
=> feat(frontend): clear token amount on token or network change

packages/frontend/package.json, packages/frontend/src/providers/SDKProvider.tsx, packages/frontend/src/utils/api.ts
- Adds `pnpm dev:local` to frontend package, allowing us to easily connect to a local backend when required for testing.
=> tooling(frontend): add package.json script to use local backend

packages/frontend/src/utils/chains.ts
- Adds Goerli to available test chains on the frontend 
- One liner, backend does not support this yet
=> frontend: add goerli to available chains

packages/frontend/src/hooks/useApprove.tsx
- Show a toast after approving a token for trading to inform the user
https://github.com/sideshiftfi/sifi/assets/128688932/287b0b18-dc2e-4867-b197-b4ef2b30cb0e
Closes #169
=> feat(frontend): show toast after approval

packages/frontend/package.json, pnpm-lock.yaml
Upgrades shared-ui to 1.7.5, which is supposed to bring up the coins with balances to the top in `TokenSelector`.
=> chore(frontend): upgrade @sifi/shared-ui to 1.7.5

packages/hardhat/.gitignore, packages/hardhat/contracts/facets/WarpLink.sol, packages/hardhat/contracts/init/InitLibWarp.sol, packages/hardhat/contracts/interfaces/IWarpLink.sol, packages/hardhat/contracts/interfaces/external/IStargateRouter.sol, packages/hardhat/contracts/libraries/LibWarp.sol, packages/hardhat/deploy-helpers/addresses.ts, packages/hardhat/deploy/003_facets.ts, packages/hardhat/hardhat.config.ts, packages/hardhat/helper-hardhat-config.ts, packages/hardhat/test/foundry/Curve.t.sol, packages/hardhat/test/foundry/UniV2LikeFacet.t.sol, packages/hardhat/test/foundry/UniV3Like.t.sol, packages/hardhat/test/foundry/WarpLink.t.sol, packages/hardhat/test/foundry/helpers/Networks.sol
This PR adds support for the first jump (bridge), Stargate
Note that the LayerZero cross-chain messaging fee is paid in the native token
- feat(hardhat): add goerli testnet
- feat(hardhat): add stargate jump
Gas usage is up, likely from extra checks and fields added to the transient storage
```
testFork_deadline() (gas: 0 (0.000%)) 
testFork_warpCurveDaiToGusd() (gas: 531 (0.092%)) 
testFork_univ3LikeMulti() (gas: 515 (0.099%)) 
testFork_swapSingleUniV3() (gas: 499 (0.112%)) 
testFork_univ2LikeMulti() (gas: 516 (0.123%)) 
testFork_collectFee() (gas: 529 (0.129%)) 
testFork_swapSingleUniV2Sushi() (gas: 529 (0.166%)) 
testFork_positiveSlippage() (gas: 529 (0.169%)) 
testFork_Unwrap() (gas: 518 (0.189%)) 
testFork_warpCurveV1AndFactory() (gas: 868 (0.189%)) 
testFork_swapSingleUniV3() (gas: …
```
=> feat(hardhat): add stargate jump

packages/hardhat/.gitignore, packages/hardhat/contracts/facets/WarpLink.sol, packages/hardhat/contracts/interfaces/IWarpLink.sol, packages/hardhat/contracts/interfaces/external/IStargateReceiver.sol, packages/hardhat/deploy-helpers/addresses.ts, packages/hardhat/deploy/003_facets.ts, packages/hardhat/foundry.toml, packages/hardhat/hardhat.config.ts, packages/hardhat/script/jump.sol, packages/hardhat/test/foundry/WarpLink.t.sol, packages/hardhat/test/foundry/helpers/IStargateRouter.sol, packages/hardhat/test/foundry/helpers/Networks.sol
Add support for running WarpLink commands after a Stargate jump
When a payload is passed, the recipient of the tokens becomes the Sifi contract. The Stargate router will call `sgReceive` on the Sifi contract, which in turn calls `warpLinkEngage` as if it was a user of itself.
Keep in mind that this behavior causes `msg.sender` and `address(this)` to be the Sifi contact.
The original plan was to write `sgReceive` similar to `warpLinkEngage`, meaning it calls `engageInternal`, but this does not allow handling reverts.
- fix(harhat): remove unused `t.deadline` from WarpLink
- feat(hardhat): support post-jump commands for Stargate
=> feat(hardhat): support post-jump commands for Stargate

packages/frontend/src/components/CreateSwap/CreateSwap.tsx, packages/frontend/src/components/CreateSwapButtons/ApproveButton.tsx, packages/frontend/src/components/CreateSwapButtons/SwitchNetworkButton.tsx, packages/frontend/src/hooks/useAllowance.tsx, packages/frontend/src/hooks/useApprove.tsx, packages/frontend/src/hooks/useCullQueries.tsx, packages/frontend/src/hooks/useQuote.tsx, packages/frontend/src/hooks/useSwapFormValues.tsx
Adds a hook so that we don't have to do the `SwapFormKeys` and `useWatch` dance in order to access values from the form state.
=> refactor(frontend): add useSwapFormValues hook

packages/frontend/package.json, packages/frontend/src/components/ChainSelector/ChainSelector.stories.tsx, packages/frontend/src/components/ChainSelector/ChainSelector.tsx, packages/frontend/src/components/CreateSwap/CreateSwap.tsx, packages/frontend/src/components/CreateSwapButtons/CreateSwapButtons.tsx, packages/frontend/src/components/CreateSwapButtons/SwitchNetworkButton.tsx, packages/frontend/src/components/Header/Header.tsx, packages/frontend/src/components/HeaderChainSelector/HeaderChainSelector.stories.tsx, packages/frontend/src/components/HeaderChainSelector/HeaderChainSelector.tsx, packages/frontend/src/components/Hero/Hero.tsx, packages/frontend/src/components/NetworkSelector/NetworkSelector.tsx, packages/frontend/src/components/TokenSelector/TokenSelector.tsx, packages/frontend/src/hooks/useAllowance.tsx, packages/frontend/src/hooks/useApprove.tsx, packages/frontend/src/hooks/useCullQueries.tsx, packages/frontend/src/hooks/useDefaultTokens.tsx, packages/frontend/src/hooks/useFetchTokens.tsx, packages/frontend/src/hooks/useMulticallTokenBalance.tsx, packages/frontend/src/hooks/useQuote.tsx, packages/frontend/src/hooks/useSpendableBalance.ts, packages/frontend/src/hooks/useTokenBalance.tsx, packages/frontend/src/providers/SwapFormProvider.tsx, packages/frontend/src/providers/TokensProvider.tsx, packages/frontend/src/utils/featureFlags.ts, packages/frontend/src/utils/firstAndLast.ts, packages/frontend/src/utils/index.ts, packages/frontend/src/utils/tests/firstAndLast.test.ts, pnpm-lock.yaml
Sets up the cross-chain jump, i.e. bridging anything to anything on the frontend. This is a big one, but everything appears to be working.
- Contains #267.
- Remove `enableMultiChains` flag [0485c4b](https://github.com/sideshiftfi/sifi/pull/264/commits/0485c4bbfa079cfa19827dd4485b24d47e534ccb)
- Upgrade @sifi/sdk to 1.9.0 [a8bce34](https://github.com/sideshiftfi/sifi/pull/264/commits/a8bce3477fb9edd4acc2722ac44c4eff9373c05c)
- Add an util for displaying first and last characters of a string [23ebaab](https://github.com/sideshiftfi/sifi/pull/264/commits/23ebaab682d9b35f2b0acc4cd8d3d55fda8be0e7)
- Renamed `NetworkSelector` to `HeaderChainSelector`. [9f93a7b](https://github.com/sideshiftfi/sifi/pull/264/commits/9f93a7b0f2b6ca0e190a84c800def69f3d25c893) We now have 2 very similar components …
=> feat(frontend): cross chain jump

packages/frontend/src/hooks/useCullQueries.tsx, packages/frontend/src/hooks/useQuote.tsx, packages/frontend/src/utils/queries.tsx
With multichain added, we need to add the chain ids as query keys to ensure we appropriately cull queries when switching chains.
We otherwise end up with quotes showing for incorrect pairs if a user switches networks and tokens quickly.
- Swapping chains and tokens quickly no longer results in quotes being shown for pairs other than the currently selected ones.
=> fix(frontend): handle multichain quote query culling

packages/frontend/src/hooks/useQuote.tsx
Bug reproduced by:
- Selecting Arbitrum as destination network
- Fetching quote for 44 USDC -> USDT 
- Changing settle token to USDC (arb) (quote fails for me)
- Quote for USDC -> USDT swap still appears, but shift button is disabled
- Always clear the 'toAmount' field when toToken, fromToken or toAmount changes
- Bug described above no longer occurs.
=> fix(frontend): always reset 'toAmount' value on input change

packages/frontend/src/providers/TokensProvider.tsx, packages/frontend/src/utils/featureFlags.ts
- Flips token trading by address flag
- Passes lowercased address to backend (broken otherwise, not certain why)
- Icons do not load due to a Coingecko change  - requires a backend change (made an issue)
=> feat(frontend): enable token trading by address

packages/frontend/src/hooks/useQuote.tsx
Only retry failed quotes once.
With multichain - users will have failing quotes more often, at least for now. Current we are retrying 4 times which leads to slow feedback and is frustrating.
If a quote has failed once it is very likely to fail again, retrying once is much faster and feels a lot better in testing.
=> feat(frontend): only retry once on failed quote

packages/frontend/src/App.tsx, packages/frontend/src/AppProvider.tsx, packages/frontend/src/components/CreateSwap/CreateSwap.tsx, packages/frontend/src/hooks/useSyncTokenUrlParams.ts, packages/frontend/src/hooks/useTokenUrlParams.ts, packages/frontend/src/utils/chains.ts, packages/frontend/src/utils/tokens.ts
- Updates url to reflect the current swap
- Sets default to from chain and swap from url on page load
- Introduces routes, uses hash router (required to access the routes through IPFS)
- Fetching arbitrary tokens by url is not supported here yet - to be dealt with in a follow up
- Can store these in localstorage as well as a follow up
https://github.com/sideshiftfi/sifi/assets/112887817/e647994f-188d-4b6c-a5a1-f473eb9d2956
=> feat(frontend): dynamic swap routing

packages/frontend/src/components/CreateSwap/CreateSwap.tsx, packages/frontend/src/utils/featureFlags.ts
Hides the `SwapInformation` component (current only displaying the incorrect gas estimate)
=> feat(frontend): hide swap information, feature flag

packages/frontend/src/providers/TokensProvider.tsx
- Only re-fetches `toTokens` and `fromTokens` when the target chain id does not match the already fetched tokens.
- Fixes an issue where a token fetched by id would immediately be replaced with re-fetched tokens.
Before:
https://github.com/sideshiftfi/sifi/assets/112887817/5c03e30b-a8ac-4b21-8318-41c91571aa74
After:
https://github.com/sideshiftfi/sifi/assets/112887817/6413e680-cc22-4e01-9c77-1401b574a002
See videos
=> fix(frontend): fetch token by address

packages/frontend/src/components/TokenSelector/TokenSelector.tsx
Display the network icon in TokenSelector to help the user remember what they are selecting.
=> feat(frontend): display chain icons in TokenSelector

packages/frontend/src/components/CreateSwapButtons/CreateSwapButtons.tsx
- Remove the check if there's a quote for determining whether the user has sufficient balance. This caused the insufficient balance to occasionally show if a quote could not be fetched even though they might have enough balance
Example of a case where a quote could not be fetched:
=> fix(frontend): insufficient balance label shows with sufficient balance

packages/frontend/src/components/CreateSwap/CreateSwap.tsx, packages/frontend/src/hooks/useUsdValue.ts
- Add `useUsdValue` hook to Frontend
- Show usd value for swap on both sides
⚠️ This PR uses #286 
Closes #136
=> feat(frontend): show usd value in shift input

packages/frontend/src/components/CreateSwapButtons/CreateSwapButtons.tsx
- Fix chain equality check in `CreateSwapButton` used for displaying the same token pair label
Before:
After:
=> fix(frontend): same token pair label on swap button

packages/frontend/src/hooks/useQuote.tsx
- Add extra check to `isSameTokenPair` in `useQuote` for matching Chain IDs, so we can still request quotes for tokens with the same address as long as the chains are different
- Tested by requesting quotes for tokens with the same address on different chains
=> fix(frontend): no quote fetched for cross-chain tokens with same address

packages/frontend/src/utils/chains.ts
- Special case for BSC chain name, allowing the name to be displayed in one line in network selector dropdowns.
- This is the official name now, anyway: https://www.bnbchain.org/en
=> feat(frontend): filter bsc name

packages/frontend/src/App.tsx, packages/frontend/src/hooks/useReferrer.ts, packages/frontend/src/hooks/useSyncTokenUrlParams.ts, packages/frontend/src/utils/routes.ts
- Using search params with the hash router the way we want to is broken when combined with the token swap routing.
- Uses routes to handle referrer addresses
- Valid routes for referrers are now `sifi.org/#/<ADDRESS><BASIS_POINTS>` or `sifi.org/#/<TOKEN_ADDRESS_1><CHAIN_ID_1>/<TOKEN_ADDRESS_2><CHAIN_ID_2>/<ADDRESS><BASIS_POINTS>`
- The `#` is required.
=> fix(frontend): use routes for referral links

packages/subgraph/.gitignore, packages/subgraph/abis/ERC20.json, packages/subgraph/abis/IERC20.json, packages/subgraph/abis/OffchainOracle.json, packages/subgraph/abis/SifiDiamond.json, packages/subgraph/bin/deploy.sh, packages/subgraph/bin/import-abis.sh, packages/subgraph/networks.json, packages/subgraph/package.json, packages/subgraph/schema.graphql, packages/subgraph/src/constants.ts, packages/subgraph/src/helpers.ts, packages/subgraph/src/mappings/warp.ts, packages/subgraph/src/services/pricing.ts, packages/subgraph/src/services/stats/all-time.ts, packages/subgraph/src/services/tokens.ts, packages/subgraph/subgraph.yaml, packages/subgraph/tsconfig.json, pnpm-lock.yaml
We can query the our subgraph using GraphQL with the endpoint `https://gateway-arbitrum.network.thegraph.com/api/3e9d2f58d24bcd5d854ba4c4c8df5c3b/subgraphs/id/G316MkVLSw1ksstmonpSQ1UEBUWmRSZf4QkoRA5CN4TA` for Ethereum (aka mainnet)
And `https://gateway-arbitrum.network.thegraph.com/api/3e9d2f58d24bcd5d854ba4c4c8df5c3b/subgraphs/id/BVexPGe3pnB7Mw7ajFkEDQJ8XY8XdVKbAL37ydmorhSQ` for Arbitrum (aka `arbitrum-one`)
I'll publish to the remaining chains later.
This API key is *not secret*. It incurs some cost, but can only be used to call the sifi graph.
There is one endpoint ("deployment") per network. If we want to show the volume total for all networks, we need to make multiple GraphQL requests.
Here's an example query:
```graphql
{
allTimeStats(id: "current") {
id
warpCount
volumeUsd
} …
```
=> feat(subgraph): add subgraph

packages/frontend/package.json, packages/frontend/src/App.tsx, packages/frontend/src/components/Stats/Stats.tsx, packages/frontend/src/hooks/useAllTimeStats.tsx, packages/frontend/src/hooks/useMulticallTokenBalance.tsx, packages/frontend/src/subgraph.json, packages/frontend/src/utils/numberWithCommas.tsx, packages/frontend/tsconfig.json, pnpm-lock.yaml
- Display the all-time USD volume combined of all chains
- Uses [subgraph.json](https://github.com/sifiorg/sifi/blob/0137f034b0ebfeaedabe3268b5abca8a9a95ef4c/packages/frontend/src/subgraph.json) in the suggested format by @xykota 
- We can find a better placement in the future
- Vite had to be upgraded, otherwise GraphQL fails with exotic errors
Closes #355
=> feat(frontend): show all-time USD volume

packages/frontend/src/hooks/useDefaultTokens.tsx, packages/frontend/src/providers/SwapFormProvider.tsx
Trivial, no template.
- Set default target chain to Arbitrum
- Set default to token to USDC
Better demonstrates cross chain capabilities to new users.
=> feat(frontend): set default swap pair to eth mainnet -> usdc arbitrum

packages/frontend/src/App.tsx, packages/frontend/src/components/RecentWarps/RecentWarps.stories.tsx, packages/frontend/src/components/RecentWarps/RecentWarps.tsx, packages/frontend/src/hooks/useRecentWarps.tsx, packages/frontend/src/utils/getIconFromSymbol.tsx, packages/frontend/src/utils/index.ts
- Displays the 5 latest swaps from the subgraph.
- The component was based on Recent Shifts.
- Base and BNB does not return a value from the API, seems like not a frontend issue.
- Works on all browsers, works on mobile.
- Could not get msw to mock loading/error states in Storybook.
- We could later add links to explorers.
Closes #357
=> feat(frontend): show recent swaps

packages/frontend/src/components/CreateSwap/CreateSwap.tsx
- Hides max amount if the user is connected to the wrong network.
- Preferable to just passing the fromAmount balance (which we have access to), as we want to be passing the _spendable_ balance, not the total (gas)
- "Max: 0" no longer shows if from input is populated, and user is connected to wrong network.
Closes #365
=> fix(frontend): hide max amount in input if user is connected to wrong network

packages/frontend/index.html, packages/frontend/src/App.tsx, packages/frontend/src/components/CreateSwap/CreateSwap.tsx, packages/frontend/src/components/Footer/Footer.tsx, packages/frontend/src/components/Header/Header.tsx, packages/frontend/src/components/Hero/Hero.tsx, packages/frontend/src/components/RecentWarps/RecentWarps.tsx, packages/frontend/src/components/Stats/Stats.tsx, packages/frontend/src/texts.ts
- Based on https://discord.com/channels/1032578356241244160/1037692726059225131/1169232140462989362
- Remove links from the top nav, place them in the footer instead
- Shorten titles, "Swap" and "Recent"
- Replace description based on https://discord.com/channels/1032578356241244160/1037692726059225131/1169234680592220170
- Move All-Time Volume under the paragraph, tone down it's styling.
- Always center CreateSwap - looks best with the warp animation. Ensure that other sections don't distract users on any screen sizes
=> feat(frontend): simplify copy and layout

packages/frontend/src/utils/chains.ts
- Replace default Snowtrace explorer link for AVAX with Avascan, prior to deprecation
- Tested with https://github.com/sifiorg/sifi/pull/393, transaction is correctly linked to for AVAX :heavy_check_mark:
=> feat(frontend): replace avax explorer link

packages/sdk/src/Sifi.ts, packages/sdk/src/helpers.ts
Passing the entire quote instead of relying on a backend to store the quote and retrieve it by ID enables a few different features later:
- The SDK can call a different path finder instance/type to build the tx from the quote
- The SDK could contain the code the builds the tx from the quote, removing the need for the getSwap call
The code quality of the SDK is still pretty low, but it's small enough for now to live with.
The types of `quote.source.data` are not included in this PR. Once we add them, the frontend can render a "swap diagram" that shows how the swap will route through various tokens, splits, etc.
=> feat(sdk): pass entire quote to getSwap

packages/frontend/src/components/RecentWarps/RecentWarps.tsx, packages/frontend/src/hooks/useRecentWarps.tsx
- Fetch swaps for all supported chains, and show them in the RecentSwaps Component
Closes #386
=> feat(frontend): show recent swaps across all chains

packages/frontend/src/components/RecentWarps/RecentWarps.tsx, packages/frontend/src/hooks/useRecentWarps.tsx
- Show Transaction Link to Blockchain Explorer in RecentWarps Component
Closes #387
=> feat(frontend): tx link in recent warps

packages/frontend/src/hooks/useFetchTokens.tsx, packages/frontend/src/providers/TokensProvider.tsx
Allows fetching chains from multiple networks. This is required for the Dashboard, as we have to work with tokens on different networks there. #401
=> feat(frontend): allow fetching tokens from multiple networks

packages/frontend/src/App.tsx, packages/frontend/src/components/Footer/Footer.tsx, packages/frontend/src/components/HeaderMenu/HeaderMenu.tsx, packages/frontend/src/constants.ts, packages/frontend/src/hooks/useFetchTokens.tsx, packages/frontend/src/hooks/usePartnerData.tsx, packages/frontend/src/hooks/usePartnerTokens.tsx, packages/frontend/src/hooks/usePartnerWithdraw.tsx, packages/frontend/src/pages/Dashboard.tsx
Users can collect referral rewards by referring other users. The Dashboard is where they can see related stats and withdraw rewards.
- Adds the new Dashboard page, and links in the header and footer for navigation.
- Adds two new hooks. `usePartnerToken` retrieves the partner token data from all the supported chains via subgraphs. `usePartnerWithdraw` handles withdrawing tokens via interacting with the `StarVault` smart contract.
- Adds `tokensByAddress` token dictionary to `useFetchTokens` so tokens can easily found by their address
- If the user is not connected to the correct network, the Withdraw button triggers a network switch first. We should probably display a network selector akin to the one reverted in #414, but it should show the currently active chain, not the one selected in …
=> feat(frontend): add partner dashboard

packages/frontend/package.json, packages/frontend/src/components/Header/Header.tsx, packages/frontend/src/components/RecentWarps/RecentWarps.tsx, pnpm-lock.yaml
Upgrades shared-ui to the latest version, which contains several fixes, including one for #442.
Closes #422.
=> chore(frontend): upgrade shared-ui to 1.8.11

packages/frontend/src/hooks/useQuote.tsx, packages/frontend/src/utils/queries.tsx
- Refactor `useQuote` to handle refetching, and when to clear the inputs by removing the original `useEffect` that caused this issue
- Restructure the query keys. React Query knows when to re-run the query based on when the query key changes, however it can't properly do that, because inside of the query key is an object with all the properties, instead of just strings which is more failproof
https://github.com/sifiorg/sifi/assets/128688932/7207adbc-7ef5-4fa0-93cb-3325eb038020
Closes #415
=> fix(frontend): to amount gets cleared when approval is needed

packages/frontend/src/components/RecentWarps/RecentWarps.tsx, packages/frontend/src/utils/getIconFromSymbol.tsx
Quick fix - this is causing the site to crash so we should merge this asap.
Below token was causing a crash in recent deposits when trying to fetch a null token symbol.
=> fix(frontend): handle null token symbols

packages/frontend/src/components/Header/Header.tsx
Re-adds the Discord and Docs links to the header, to make it easier for users to find them. 
Tested by clicking on them.
=> feat(frontend): add nav links

packages/frontend/src/components/CreateSwap/CreateSwap.tsx
Use LayerZero Scan explorer link for Jumps, as the native chain explorer only shows half the picture.
=> feat(frontend): use LayerZero Scan for jumps

packages/frontend/src/components/CreateSwap/CreateSwap.tsx
Adds `autoClose: false` so that the success TX link does not disappear, as this is the only way for users to track Jumps.
Toasts will get significantly more improvement in #486, this is just a quick fix.
=> feat(frontend): do not auto close success toast

packages/frontend/src/components/CreateSwap/CreateSwap.tsx, packages/frontend/src/components/CreateSwapButtons/CreateSwapButtons.tsx, packages/frontend/src/hooks/useDepositMax.tsx, packages/frontend/src/hooks/useExecuteSwap.tsx
It's quite difficult to work with CreateSwap, it got quite bloated. The new swap modal (#453) also requires some preliminary refactors, hence this PR.
- Creates new useExecuteSwap hook so the execution can be reused and moves over the related logic.
- Creates new useDepositMax hook and moves over the related logic.
=> refactor(frontend): CreateSwap

packages/frontend/package.json, packages/frontend/src/components/CreateSwapButtons/CreateSwapButtons.tsx, packages/frontend/src/hooks/useExecuteSwap.tsx, packages/frontend/src/hooks/useRefetchBalances.tsx, packages/frontend/src/hooks/useSwapToast.tsx, pnpm-lock.yaml
- Render a single toast and update it's state to communicate the status of the swap. This is the MVP version of the Swap Modal (#453). The toast is unclosable until the swap is completed. Uses `getJump` to track the status of jumps.
- Update balances when transactions are executed and completed. Refactored logic to `useRefetchBalances` hook.
- Update the execute button's label to show "Execute Swap" or "Execute Jump" [91139f6](https://github.com/sifiorg/sifi/pull/503/commits/91139f63d1b9d287c28020d4b46c0b4ee485b1d2)
- Adjust space travel animation so it is synced with the jump. Decided to slow down during "arriving", as it is fairly long and we don't want users to get an epileptic seizure.
1. Communicate what swap is being executed. Perhaps show icons as part of the loading animation. …
=> feat(frontend): display swap status in a single toast

packages/frontend/package.json, pnpm-lock.yaml
Fixed the `type` issue by omitting `type` from `ToastOptions` in the latest `shared-ui` build. This PR fixes the TypeScript error so we can continue deploying.
~Can't figure out why the `loading` prop is not working. `ToastType` clearly contains it and everything in the shared-ui lib looks fine. Typescript accepts it when passed directly to `Toast`, but not when used in `showToast`. The UI works as expected. This PR temporary fixes it so that we can continue deploying.~
=> fix(frontend): temp "loading" Toast type

packages/frontend/src/App.tsx, packages/frontend/src/AppProvider.tsx, packages/frontend/src/components/Footer/Footer.tsx, packages/frontend/src/components/HeaderMenu/HeaderMenu.tsx, packages/frontend/src/config.ts, packages/frontend/src/hooks/useExecuteSwap.tsx, packages/frontend/src/modals/ReferralModal/ReferralModal.tsx, packages/frontend/src/providers/ReferralModalProvider.tsx
- Adds a referral modal. 
- Places links in the Menu and in the footer.
- The URL does not contain `feeBps`, sticking to default. UI shows 1% because 50% goes to the protocol.
- Uses context to keep track of the state as we have the modal in multiple places.
- Triggers the share action on mobile, copies to clipboard on desktop.
- Shows toast after successful copy on desktop.
- Shows connect wallet if the user is not connected.
=> feat(frontend): add referral modal

packages/frontend/src/components/RecentWarps/RecentWarps.tsx
Fixes the table alignment, headings are now aligned to the columns.
=> fix(frontend): recent table header alignment

packages/frontend/src/components/Hero/Hero.tsx
At certain medium screen sizes, the app got too squished. This one liner fixes this.
=> style(frontend): fix medium breakpoint width

packages/frontend/src/config.ts, packages/frontend/src/hooks/useExecuteSwap.tsx
If only `referralAddress` in localstorage, due to the user being referred via a URL without a `feeBps` specified in it, use `feeBps` of `40` when executing a swap.
=> feat(frontend): set fee bps to 40 with partner address only

packages/frontend/package.json, pnpm-lock.yaml
Upgrades shared-ui to the latest version.
- HeaderMenu no longer remains open when Shift History is opened.
- Builds correctly.
=> chore(frontend): upgrade @sifi/shared-ui to 2.0.1

packages/frontend/src/components/CreateSwap/CreateSwap.tsx, packages/frontend/src/hooks/useSuggestMevProtection.ts, packages/frontend/src/utils/localStorageKeys.ts
- The first time a user connects to the site on mainnet, suggest they use the MEVBlocker RPC to prevent attacks.
- There is no way to reliably check if a user is already using MEVBlocker
- Brave Wallet responds `true` to `eth_mevblocker`, but Metamask does not.
- Removed check entirely since we cannot guarantee a consistent experience cross wallet.
- Relying solely on local storage flag.
- Rather than addding the network directly, we link a user to https://mevblocker.io/#rpc so they can learn what they are doing prior to adding the RPC. (They have a convenient button on their site) 
=> feat(frontend): prompt user to use mevblocker once

packages/frontend/src/components/Button/Button.tsx, packages/frontend/src/components/Button/Button.types.ts, packages/frontend/src/components/ConnectWallet/ConnectWallet.tsx, packages/frontend/src/components/HeaderMenu/HeaderMenu.tsx
Adds the Connect Wallet button to the header as per [this request on Discord](https://discord.com/channels/1032578356241244160/1164402982251675649/1196732960372695081). For this to work, had to export the `ButtonSizes` type from Button.
=> feat(frontend): display Connect Wallet button in Header

packages/frontend/package.json, packages/frontend/src/components/TokenSelector/TokenSelector.tsx, packages/frontend/src/providers/WalletBalancesProvider.tsx, pnpm-lock.yaml
- Adds the loading state for token balances.
- Only display the loading state on initial fetch. Would be annoying UX for refetches to hide the balances.
https://github.com/sifiorg/sifi/assets/128667801/caff03bd-4ae9-4b0e-ab58-0d40b4ec5220
=> feat(frontend): add balance loading state to TokenSelector
