pnpm-lock.yaml

@sifi/sdk got linked in #123 in frontend. We don't want this on prod, this PR fixes it by running `pnpm unlink @sifi/sdk`.
This issue is blocking the deployment via Fleek.

fix(frontend): unlink @sifi/sdk

---

packages/sdk/package.json
packages/sdk/src/Sifi.ts

- feat(sdk): add `getToken`
- chore(sdk): v1.5.0

sdk get token

---

packages/frontend/package.json
packages/frontend/src/index.d.ts
packages/frontend/vite.config.ts
pnpm-lock.yaml

Adds SVGR support to the Frontend so we can use SVGs as React Components
Closes #147

feat(frontend): add svgr support

---

packages/frontend/package.json
packages/frontend/src/components/CreateSwapButtons/CreateSwapButtons.tsx
pnpm-lock.yaml

- Update `@sifi/shared-ui` to `1.7.3` to fix comma inputs not working
- Add '0' as fallback in case the Input is empty to CreateSwapButtons
https://github.com/sideshiftfi/sifi/assets/128688932/69189186-b98e-41bf-9256-51077cc973e4
Closes #159

fix(frontend): app crashes after various inputs

---

packages/frontend/src/components/CreateSwap/CreateSwap.tsx

- Adds refetch to balances
- Resets the form by clearing `fromAmount`

feat(frontend): reset form after success

---

packages/sdk/src/Sifi.ts

- minor(sdk): improve Swap tsdoc
- feat(sdk): export ETH_ADDRESS

sdk minor aug17

---

packages/hardhat/contracts/v2/facets/UniV2LikeFacet.sol
packages/hardhat/contracts/v2/facets/UniV2RouterFacet.sol
packages/hardhat/contracts/v2/init/DiamondMultiInit.sol
packages/hardhat/contracts/v2/init/InitLibWarp.sol
packages/hardhat/contracts/v2/interfaces/IUniV2Like.sol
packages/hardhat/contracts/v2/interfaces/external/IUniswapV2Factory.sol
packages/hardhat/contracts/v2/libraries/LibUniV2Like.sol
packages/hardhat/contracts/v2/libraries/LibUniV2Router.sol
packages/hardhat/contracts/v2/libraries/LibWarp.sol
packages/hardhat/deploy/addresses.ts
packages/hardhat/deploy/helpers.ts
packages/hardhat/deploy/v2/003_facets.ts
packages/hardhat/hardhat.config.ts
packages/hardhat/test/foundry/v2/DiamondCutFacet.t.sol
packages/hardhat/test/foundry/v2/UniV2LikeFacet.t.sol
packages/hardhat/test/foundry/v2/helpers/Mainnet.sol

- minor(hardhat): use 2x gas price on sepolia
- feat(hardhat): add multi init
- refactor(hardhat): extract applySlippage to LibWarp
- feat(hardhat): add univ2-like warps

feat(hardhat): univ2-like warps

---

packages/hardhat/contracts/facets/UniV2LikeFacet.sol
packages/hardhat/contracts/interfaces/IUniV2Like.sol
packages/hardhat/contracts/libraries/LibUniV2Like.sol
packages/hardhat/test/foundry/UniV2LikeFacet.t.sol

fix(hardhat): allow uniswapV2LikeExactInput with different pool fees

---

packages/frontend/tailwind.config.cjs

- Change Tailwind Config Dark Theme to use `data-theme` attribute
Closes #190

fix(frontend): tailwind theme is based on system preference

---

packages/hardhat/test/foundry/UniV2LikeFacet.t.sol

This fixes the failing CI by making sure the Arbitrum fork test passes.
`ARBITRUM_ONE_RPC_URL ` is needed in env
closes #214

fix(hardhat): fix Arbitrum fork test

---

packages/frontend/.storybook/main.cjs

Applies the same fix as https://github.com/sideshiftfi/sifi/pull/208 to storybook vite config, fixing it locally.
Closes #207

fix(frontend): optimize wagmi deps in storybook vite config

---

packages/frontend/src/components/CreateSwap/CreateSwap.tsx
packages/frontend/src/constants.ts
packages/frontend/src/hooks/useSpendableBalance.ts

- Add Max Button to Shift Input
- Calculate max based on Balance, and max gas fees in case of ETH
https://github.com/sideshiftfi/sifi/assets/128688932/7af3fbe9-4764-45f3-aa25-34c708368375

feat(frontend): implement max button in shift input

---

packages/sdk/src/Sifi.ts

- minor(sdk): improve Quote.approveAddress doc
- feat(sdk): add permit2

sdk permit

---

packages/frontend/src/providers/TokensProvider.tsx

Fixes the typo that's blocking the release.

fix(frontend): build error due to selectedChain typo

---

packages/frontend/src/utils/chains.ts

- Adds Sepolia to list of supported chains on localhost

feat(frontend): add sepolia to chainlist on localhost

---

packages/frontend/package.json
pnpm-lock.yaml

- Updates Shared-UI to latest version to incorporate latest changes and improvements
- No unexpected changes with this update

deps(frontend): update shared-ui to 1.7.4

---

packages/frontend/src/assets/icons/close.svg
packages/frontend/src/components/ConnectWallet/ConnectWallet.tsx

- Use Shared-UI Modal for ConnectWalletModal

refactor(frontend): use shared-ui modal for connect wallet

---

packages/frontend/src/components/CreateSwap/CreateSwap.tsx
packages/frontend/src/hooks/useReferrer.ts
packages/frontend/src/utils/localStorageKeys.ts
packages/frontend/src/utils/routes.ts

- Implements referral system in Frontend. When going to a `/?ref=<walletaddress><optional-fee-bps>` route, the wallet address and fee will be set in local storage and used when creating a swap
- Tested by creating a swap with partner address and feebps passed in on the smart contract

feat(frontend): handle referrals

---

packages/frontend/src/components/CreateSwap/CreateSwap.tsx
packages/frontend/src/utils/getTokenWithNetwork.tsx

- Display network icons in ShiftInput
- Contains #266

refactor(frontend): display network icons in ShiftInput

---

packages/sdk/src/Sifi.ts

- Add `getUsdPrice` function to the sdk to get usd price for a token
- Tested in Frontend

feat(sdk): add token usd price function

---

packages/frontend/src/App.tsx

The FAQ is outdated and is being hidden for now.

frontend: remove faq from homepage

---

packages/frontend/src/hooks/usePermit2.ts

- fix(frontend): set permit expiration to 1h
- minor(frontend): remove unused import

permit exp

---

packages/frontend/index.html
packages/frontend/src/components/CreateSwapButtons/CreateSwapButtons.tsx
packages/frontend/src/components/Footer/Footer.tsx
packages/frontend/src/components/Hero/Hero.tsx
packages/frontend/src/texts.ts

- Updates the copy as suggested by Xykota. Both in components and in index.html.
- Separates reused strings into a texts file.

feat(frontend): update copy

---

packages/hardhat/contracts/facets/UniV2LikeFacet.sol
packages/hardhat/test/foundry/Curve.t.sol
packages/hardhat/test/foundry/LibStarVault.t.sol
packages/hardhat/test/foundry/Stargate.t.sol
packages/hardhat/test/foundry/UniV2LikeFacet.t.sol
packages/hardhat/test/foundry/UniV2RouterFacet.int.t.sol
packages/hardhat/test/foundry/UniV2RouterFacet.t.sol
packages/hardhat/test/foundry/UniV3Like.t.sol
packages/hardhat/test/foundry/WarpLink/Arbitrum.t.sol
packages/hardhat/test/foundry/WarpLink/Goerli.t.sol
packages/hardhat/test/foundry/WarpLink/Mainnet-17853419.t.sol
packages/hardhat/test/foundry/WarpLink/Mainnet-18069811.t.sol
packages/hardhat/test/foundry/WarpLink/Mainnet-18240282.t.sol
packages/hardhat/test/foundry/WarpLink/Optimism.t.sol
packages/hardhat/test/foundry/WarpLink/Polygon.t.sol
packages/hardhat/test/foundry/WarpLink/TestBase.sol
packages/hardhat/test/foundry/helpers/FacetTest.sol
packages/hardhat/test/foundry/helpers/Networks.sol
packages/hardhat/test/foundry/helpers/UniV2.sol

- refactor(hardhat): extract WarpLink tests
- refactor(hardhat): extract warp testing utils
- fix(hardhat): fix UniV2Like amount out checks

arb failed swap

---

packages/hardhat/contracts/facets/StarVault.sol
packages/hardhat/contracts/interfaces/IStarVault.sol
packages/hardhat/contracts/libraries/LibStarVault.sol
packages/hardhat/test/foundry/LibStarVault.t.sol
packages/hardhat/test/foundry/StarVault.t.sol

These values can be pulled from a chain indexer like TheGraph. Saves up to 170K gas on swaps with a fee.

feat(hardhat): stop tracking partners/token addresses

---

packages/frontend/package.json
packages/frontend/src/components/TokenSelector/TokenSelector.tsx
packages/frontend/src/hooks/useMulticallTokenBalance.tsx
packages/frontend/src/types.ts
pnpm-lock.yaml

- Extend `useMulticallTokenBalance` hook to also return usd values
- Pass usd values down to CoinSelector
⚠️ This PR uses #322 

feat(frontend): show usd value in token selector

---

packages/frontend/package.json
packages/frontend/src/components/ConnectWallet/ConnectWallet.tsx
packages/frontend/src/components/HeaderMenu/HeaderMenu.tsx
pnpm-lock.yaml

- Uses new `shared-ui` `useWalletBranding` hook to display a user's specific browser wallet icon, rather than always using Metamask.
If applicable, include screenshots/videos of the updated UI. Use Blisk Browser to provide screenshots
of multiple screen sizes, e.g. iPhone SE, iPhone 14, iPad, desktop, etc.

feat(frontend): add browser wallet icons

---

packages/frontend/bin/import-subgraph.sh
packages/frontend/src/hooks/useAllTimeStats.tsx
packages/frontend/src/subgraph.json
packages/subgraph/deployments.json
packages/subgraph/networks-more.json
pnpm-lock.yaml

- minor(frontend): log subgraph chain id on fetch error
- minor(frontend): add tool to generate subgraph.json
- fix(subgraph): use hosted service for avalanche

subgraph avalanche fix

---

packages/frontend/src/components/Header/Header.tsx

- Add docs link to header
Closes #377

feat(frontend): add docs link

---

packages/hardhat/contracts/facets/UniV2LikeFacet.sol
packages/hardhat/test/foundry/UniV2LikeFacet.t.sol

fixup! fix(hardhat): fix uniswapV2LikeExactInput with eth input

---

packages/frontend/src/components/CreateSwapButtons/CreateSwapButtons.tsx

- Hide Approve Button when approving
Closes #391

refactor(frontend): hide cta during approve

---

packages/frontend/index.html

Adds the Plausible analytics embed code so that we can monitor website traffic.

feat(frontend): add Plausible analytics

---

packages/frontend/src/components/Footer/Footer.tsx

feat(frontend): add brand assets link to footer

---

packages/frontend/package.json
packages/frontend/src/components/Footer/Footer.tsx
packages/frontend/src/components/Header/Header.tsx
packages/frontend/src/components/HeaderMenu/HeaderMenu.tsx
packages/frontend/src/components/Link/Link.tsx
packages/frontend/tailwind.config.cjs
pnpm-lock.yaml

- Upgrades `@sifi/shared-ui` to the latest version, `1.10.2`
Closes #483

feat(frontend): update shared-ui to 1.10.2

---

packages/hardhat/foundry.toml
packages/hardhat/test/foundry/Curve.t.sol
packages/hardhat/test/foundry/StarVault.t.sol
packages/hardhat/test/foundry/Stargate.t.sol
packages/hardhat/test/foundry/UniV2LikeFacet.t.sol
packages/hardhat/test/foundry/UniV2RouterFacet.t.sol
packages/hardhat/test/foundry/UniV3Like.t.sol
packages/hardhat/test/foundry/WarpLink/Arbitrum.t.sol
packages/hardhat/test/foundry/WarpLink/Mainnet-17853419.t.sol
packages/hardhat/test/foundry/WarpLink/Mainnet-18069811.t.sol
packages/hardhat/test/foundry/WarpLink/Mainnet-18240282.t.sol
packages/hardhat/test/foundry/WarpLink/Polygon.t.sol

- fix(hardhat): remove double forking tests
- fix(hardhat): set foundry evm_version to shangai

test fork regr 2

---

packages/frontend/src/components/Hero/Hero.tsx
packages/frontend/src/providers/WagmiProvider.tsx

hotfix(frontend): site under maintantance

---

packages/frontend/package.json
packages/frontend/src/components/Hero/Hero.tsx
packages/frontend/src/providers/WagmiProvider.tsx
pnpm-lock.yaml

fix(frontend): reintroduce safe wallet connection

---

packages/hardhat/contracts/facets/Curve.sol
packages/hardhat/contracts/facets/Stateless.sol
packages/hardhat/contracts/facets/UniV2LikeFacet.sol
packages/hardhat/contracts/facets/UniV2RouterFacet.sol
packages/hardhat/contracts/facets/UniV3Like.sol
packages/hardhat/contracts/facets/WarpLink.sol
packages/hardhat/contracts/interfaces/IUniV2Like.sol
packages/hardhat/contracts/interfaces/IUniV2Router.sol
packages/hardhat/contracts/interfaces/IUniV3Like.sol
packages/hardhat/test/foundry/UniV2LikeFacet.t.sol

Arrange swap parts in a more predictable order; swap, slippage check, emit event, charge fee

feat(hardhat): improve slippage ordering

---

packages/hardhat/contracts/facets/WarpLink.sol
packages/hardhat/test/foundry/WarpLink/Mainnet-17853419.t.sol

This PR adds Stateless support to the Warp Link.
The payload for the energy shield is produced by the user. This introduces a problem, because the payload often contains input amounts. To solve this issue, the user also passes an array of offsets where the amount will be written.
**Example:**
The user wants to swap 1000 USDC for WETH on Uniswap V3 and then swap the WETH for WBTC on Balancer V2. The Warp Link does not have explicit support for Balancer V2, so this must be handled by the Warp Link.
The Warp Link is engaged with two actions:
1. Swap Uniswap V3-like
2. Stateless call to Balancer V2
The output amount from step 1. is written into the payload for step 2. using the amount offsets specified in the params for step 2.

feat(hardhat): add stateless to warp link

---

packages/subgraph/package.json
packages/subgraph/src/mappings/withdraw.ts

- fix(subgraph): ignore protocol withdrawals
- deploy(subgraph): v0.0.8

graph ignore protocol withdraw

---

packages/frontend/package.json
packages/sdk/package.json
pnpm-lock.yaml

Forgot to deploy and bump the versions in #505.

deploy(sdk): v1.12.0

---

packages/hardhat/contracts/facets/WarpLink.sol

- perf(hardhat/WarpLink): extract ensureDeliveredTokens
- perf(hardhat/WarpLink): extract createTransientStateFromParams
- perf(hardhat/WarpLink): extract warpLinkEngageRoot
- perf(hardhat/WarpLink): extract moveTokensToContract
- perf(hardhat/WarpLink): extract moveTokensTo

perf(hardhat/WarpLink): reduce bytecode size

---

packages/frontend/src/components/CreateSwap/CreateSwap.tsx
packages/frontend/src/hooks/useExecuteSwap.tsx
packages/frontend/src/mocks/quote.mocks.ts

Fixed all type issues that were blocking the build.
- The story in storybook is rendering correctly.
- CI is passing in fleek. Preview: https://bafybeianuwjuuzdvo4p4sejahi4szwmpihfcaggnoxw6x4xjflsvqglzpq.on.fleek.co/

fix(frontend): type issues
